import 'dart:convert';
import '../models/medicine.dart';
import '../models/sale.dart';
import '../models/patient.dart';
import '../services/objectbox_service.dart';

class AnalyticsHelper {
  /// Extract SaleItems from a Sale record
  static List<SaleItem> getItems(Sale sale) {
    try {
      final List decoded = jsonDecode(sale.itemsJson);
      return decoded.map((item) => SaleItem.fromJson(item)).toList();
    } catch (_) {
      return [];
    }
  }

  /// Calculates the total units sold of a specific medicine in a list of sales
  static int totalUnitsSold(int medicineId, List<Sale> sales) {
    final med = ObjectBoxService.instance.medicineBox.get(medicineId);
    final medName = med?.name.toLowerCase().trim();
    if (medName == null) return 0;

    int total = 0;
    for (final sale in sales) {
      if (sale.isReturn) continue;
      for (final item in getItems(sale)) {
        if (!item.isProcedure && item.medicineName.toLowerCase().trim() == medName) {
          total += item.qty;
        }
      }
    }
    return total;
  }

  /// Calculates total revenue generated by a specific medicine
  static double revenueForMedicine(int medicineId, List<Sale> sales) {
    final med = ObjectBoxService.instance.medicineBox.get(medicineId);
    final medName = med?.name.toLowerCase().trim();
    if (medName == null) return 0.0;

    double total = 0.0;
    for (final sale in sales) {
      if (sale.isReturn) continue;
      for (final item in getItems(sale)) {
        if (!item.isProcedure && item.medicineName.toLowerCase().trim() == medName) {
          total += item.lineTotal;
        }
      }
    }
    return total;
  }

  /// Calculates net profit generated by a specific medicine
  static double profitForMedicine(Medicine medicine, List<Sale> sales) {
    int totalSold = totalUnitsSold(medicine.id, sales);
    double revenue = revenueForMedicine(medicine.id, sales);
    double cost = medicine.purchasePrice * totalSold;
    return revenue - cost;
  }

  /// Calculates the daily sales rate (consumption rate) of a medicine over a list of sales
  static double dailyConsumptionRate(int medicineId, List<Sale> sales) {
    if (sales.isEmpty) return 0.0;
    
    final med = ObjectBoxService.instance.medicineBox.get(medicineId);
    final medName = med?.name.toLowerCase().trim();
    if (medName == null) return 0.0;

    final validSales = sales.where((s) => !s.isReturn).toList();
    if (validSales.isEmpty) return 0.0;

    validSales.sort((a, b) => a.createdAt.compareTo(b.createdAt));
    
    int totalSold = 0;
    for (final sale in validSales) {
      for (final item in getItems(sale)) {
        if (!item.isProcedure && item.medicineName.toLowerCase().trim() == medName) {
          totalSold += item.qty;
        }
      }
    }

    if (totalSold == 0) return 0.0;

    final firstDate = validSales.first.createdAt;
    final lastDate = DateTime.now();
    final days = lastDate.difference(firstDate).inDays;
    
    if (days <= 0) return totalSold.toDouble();
    return totalSold / days;
  }

  /// Calculates predicted remaining days of stock for a medicine
  static double daysOfStockRemaining(Medicine medicine, List<Sale> sales) {
    final daily = dailyConsumptionRate(medicine.id, sales);
    if (daily <= 0) return 999.0; // Infinite stock (no sales activity)
    return medicine.totalStock / daily;
  }

  /// Filters sales matching a specific DateTimeRange
  static List<Sale> filterSalesByRange(List<Sale> sales, DateTime start, DateTime end) {
    final startDay = DateTime(start.year, start.month, start.day);
    final endDay = DateTime(end.year, end.month, end.day, 23, 59, 59);
    
    return sales.where((s) {
      return s.createdAt.isAfter(startDay) && s.createdAt.isBefore(endDay);
    }).toList();
  }

  /// Aggregates sales by date for graph plotting
  static Map<DateTime, double> aggregateDailyRevenue(List<Sale> sales) {
    final map = <DateTime, double>{};
    for (final sale in sales) {
      final day = DateTime(sale.createdAt.year, sale.createdAt.month, sale.createdAt.day);
      final amount = sale.total;
      map[day] = (map[day] ?? 0.0) + amount;
    }
    return map;
  }

  /// Aggregates profit margins by date for graph plotting
  static Map<DateTime, double> aggregateDailyProfit(List<Sale> sales, List<Medicine> medicines) {
    final map = <DateTime, double>{};
    final medMap = {for (var m in medicines) m.name.toLowerCase().trim(): m};

    for (final sale in sales) {
      if (sale.isReturn) continue;
      final day = DateTime(sale.createdAt.year, sale.createdAt.month, sale.createdAt.day);
      
      double profit = 0.0;
      for (final item in getItems(sale)) {
        if (item.isProcedure) {
          profit += item.lineTotal; // 100% margin on clinical procedures
        } else {
          final med = medMap[item.medicineName.toLowerCase().trim()];
          if (med != null) {
            profit += item.lineTotal - (med.purchasePrice * item.qty);
          } else {
            profit += item.lineTotal * 0.3; // Default 30% margin fallback if medicine missing
          }
        }
      }
      
      // Deduct discount proportionally from daily profit
      double proportionalDiscount = sale.discount;
      profit -= proportionalDiscount;

      map[day] = (map[day] ?? 0.0) + profit;
    }
    return map;
  }

  /// Aggregates sales distribution by category
  static Map<String, double> getCategorySales(List<Sale> sales, List<Medicine> medicines) {
    final map = <String, double>{};
    final medMap = {for (var m in medicines) m.name.toLowerCase().trim(): m};

    for (final sale in sales) {
      if (sale.isReturn) continue;
      for (final item in getItems(sale)) {
        if (item.isProcedure) {
          map['Clinical Services'] = (map['Clinical Services'] ?? 0.0) + item.lineTotal;
        } else {
          final med = medMap[item.medicineName.toLowerCase().trim()];
          final cat = med?.category ?? 'General';
          map[cat] = (map[cat] ?? 0.0) + item.lineTotal;
        }
      }
    }
    return map;
  }

  /// Ranks all medicines by units sold in the selected list of sales
  static List<MedicinePerformance> getMedicinePerformanceLeaderboard(
      List<Medicine> medicines, List<Sale> sales) {
    final performanceMap = <int, int>{};
    final revenueMap = <int, double>{};
    final nameToIdMap = {for (var m in medicines) m.name.toLowerCase().trim(): m.id};

    for (final sale in sales) {
      if (sale.isReturn) continue;
      for (final item in getItems(sale)) {
        if (!item.isProcedure) {
          final localId = nameToIdMap[item.medicineName.toLowerCase().trim()];
          if (localId != null) {
            performanceMap[localId] = (performanceMap[localId] ?? 0) + item.qty;
            revenueMap[localId] = (revenueMap[localId] ?? 0.0) + item.lineTotal;
          }
        }
      }
    }

    final list = medicines.map((m) {
      final units = performanceMap[m.id] ?? 0;
      final rev = revenueMap[m.id] ?? 0.0;
      final cost = m.purchasePrice * units;
      final prof = rev - cost;
      
      return MedicinePerformance(
        medicine: m,
        unitsSold: units,
        revenue: rev,
        profit: prof,
      );
    }).toList();

    // Sort by units sold descending as default
    list.sort((a, b) => b.unitsSold.compareTo(a.unitsSold));
    return list;
  }

  /// Retrieves list of dead stock medicines (stock > 0 but 0 sales in the last X days)
  static List<Medicine> getDeadStock(List<Medicine> medicines, List<Sale> sales, int daysThreshold) {
    final limitDate = DateTime.now().subtract(Duration(days: daysThreshold));
    final activeProductNames = <String>{};

    for (final sale in sales) {
      if (sale.createdAt.isAfter(limitDate)) {
        for (final item in getItems(sale)) {
          if (!item.isProcedure) {
            activeProductNames.add(item.medicineName.toLowerCase().trim());
          }
        }
      }
    }

    return medicines.where((m) {
      return m.totalStock > 0 && !activeProductNames.contains(m.name.toLowerCase().trim());
    }).toList();
  }

  /// Retrieves reorder recommendations based on stock level life estimation
  static List<ReorderRecommendation> getReorderList(List<Medicine> medicines, List<Sale> sales) {
    final list = <ReorderRecommendation>[];
    
    for (final m in medicines) {
      final daily = dailyConsumptionRate(m.id, sales);
      final daysLeft = daysOfStockRemaining(m, sales);
      
      // Recommend reorder if stock is below threshold OR remaining stock life is critical (< 14 days)
      if (m.totalStock <= m.lowStockThreshold || (daysLeft < 14 && daily > 0)) {
        // Suggested reorder amount: 45 days of safety stock
        final suggestAmount = (daily * 45).ceil();
        final actualSuggest = suggestAmount > 0 ? suggestAmount : (m.lowStockThreshold * 2);

        list.add(ReorderRecommendation(
          medicine: m,
          dailyVelocity: daily,
          daysLeft: daysLeft,
          suggestedReorderQty: actualSuggest,
        ));
      }
    }

    // Sort by most urgent stock lifecycle
    list.sort((a, b) => a.daysLeft.compareTo(b.daysLeft));
    return list;
  }

  /// Computes metrics on Patient behavior & returning patients
  static PatientAnalyticsData getPatientAnalytics(List<Sale> sales, List<Patient> patients) {
    if (sales.isEmpty) {
      return PatientAnalyticsData(
        uniquePatientsServed: 0,
        repeatPatientRate: 0.0,
        averageBasketValue: 0.0,
        hourlyActivity: {},
      );
    }

    final patientsServed = <int>{};
    final patientFrequency = <int, int>{};
    double totalRevenue = 0.0;

    for (final sale in sales) {
      if (sale.isReturn) continue;
      totalRevenue += sale.total;
      
      if (sale.patientId > 0) {
        patientsServed.add(sale.patientId);
        patientFrequency[sale.patientId] = (patientFrequency[sale.patientId] ?? 0) + 1;
      }
    }

    int repeatPatients = patientFrequency.values.where((count) => count > 1).length;
    double repeatRate = patientsServed.isNotEmpty 
        ? (repeatPatients / patientsServed.length) * 100 
        : 0.0;

    final hourlyMap = <int, int>{};
    for (final sale in sales) {
      final hr = sale.createdAt.hour;
      hourlyMap[hr] = (hourlyMap[hr] ?? 0) + 1;
    }

    return PatientAnalyticsData(
      uniquePatientsServed: patientsServed.length,
      repeatPatientRate: repeatRate,
      averageBasketValue: totalRevenue / sales.length,
      hourlyActivity: hourlyMap,
    );
  }
}

class MedicinePerformance {
  final Medicine medicine;
  final int unitsSold;
  final double revenue;
  final double profit;

  MedicinePerformance({
    required this.medicine,
    required this.unitsSold,
    required this.revenue,
    required this.profit,
  });
}

class ReorderRecommendation {
  final Medicine medicine;
  final double dailyVelocity;
  final double daysLeft;
  final int suggestedReorderQty;

  ReorderRecommendation({
    required this.medicine,
    required this.dailyVelocity,
    required this.daysLeft,
    required this.suggestedReorderQty,
  });
}

class PatientAnalyticsData {
  final int uniquePatientsServed;
  final double repeatPatientRate;
  final double averageBasketValue;
  final Map<int, int> hourlyActivity;

  PatientAnalyticsData({
    required this.uniquePatientsServed,
    required this.repeatPatientRate,
    required this.averageBasketValue,
    required this.hourlyActivity,
  });
}
